# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 18:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_auto_20170709_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='posted',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
